---
#- set_fact:
#    project: '{{ item }}'

- name: Create project structure [default, writeable]
  file:
    path: '/var/www/{{ project.name }}/{{ project.environment }}/{{ item }}'
    state: directory
    owner: vagrant
    group: www-data
    mode: '2775'
  with_items: ['logs', 'releases', 'releases/current']

- name: Create project structure [default, world-writeable]
  file:
    path: '/var/www/{{ project.name }}/{{ project.environment }}/{{ item }}'
    state: directory
    owner: vagrant
    group: www-data
    mode: '2777'
  with_items: ['shared', 'sessions', 'tmp']

- name: Create nginx vhost [default]
  notify: reload nginx
  template:
    src: "{{ project.nginx_template | default('default/nginx.conf') }}"
    dest: '/etc/nginx/sites-enabled/{{ project.name }}'

- name: Create php5-fpm vhost [default]
  notify: reload php5-fpm
  template:
    src: "{{ project.php_template if project.php_template is defined else 'default/php5-fpm.conf' }}"
    dest: '/etc/php5/fpm/pool.d/devbox.{{ project.name }}.conf'
