---

- name: Protect programs to be overwritten by helpers
  fail:
    msg: '{{ item.name }} is not allowed as name!'
  when: (item.helper is defined) and (
    item.name == 'ansible' or
    item.name == 'ansible-console' or
    item.name == 'ansible-doc' or
    item.name == 'ansible-galaxy' or
    item.name == 'ansible-playbook' or
    item.name == 'ansible-pull' or
    item.name == 'ansible-vault' or
    item.name == 'aws' or
    item.name == 'composer' or
    item.name == 'modman' or
    item.name == 'n98-magerun' or
    item.name == 'n98-magerun2')
  with_items: '{{ devbox_projects }}'

- name: create shell project sync helper
  template:
    src: 'helper/project-sync-wrapper.sh'
    dest: '/usr/local/bin/{{ item.name }}'
    owner: 'vagrant'
    group: 'vagrant'
    mode: '0755'
  when: item.helper is defined
  with_items: '{{ devbox_projects }}'