---
project_user: vagrant
php5_fpm_remove_default_pool: false
nginx_remove_default_vhost: false

mariadb_users:
  - name: root
    password: root
    host: "%"
    priv: '*.*:ALL,GRANT' #SELECT,INSERT,UPDATE,DELETE,CREATE,ALTER,INDEX,DROP,CREATE TEMPORARY TABLES,CREATE_VIEW,SHOW VIEW,EVENT,TRIGGER,LOCK TABLES,REFERENCES'
    append_privs: true

# php.ini (cli) settings
php5_cli_ini_expose_php: On
php5_cli_ini_memory_limit: 512M
php5_cli_ini_max_execution_time: 300
php5_cli_ini_max_input_time: 60
php5_cli_ini_max_input_vars: 5000
php5_cli_ini_realpath_cache_size: 32K
php5_cli_ini_realpath_cache_ttl: 120
php5_cli_ini_upload_max_filesize: 64M
php5_cli_ini_post_max_size: 32M
php5_cli_ini_date_timezone: "Europe/Berlin"
php5_cli_ini_sendmail_path: "/usr/sbin/sendmail -t -i"
php5_cli_ini_error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
php5_cli_ini_display_errors: "On"
php5_cli_ini_display_startup_errors: "Off"

# php.ini (fpm) settings
php5_fpm_ini_expose_php: On
php5_fpm_ini_memory_limit: 512M
php5_fpm_ini_max_execution_time: 300
php5_fpm_ini_max_input_time: 60
php5_fpm_ini_max_input_vars: 5000
php5_fpm_ini_realpath_cache_size: 32K
php5_fpm_ini_realpath_cache_ttl: 120
php5_fpm_ini_upload_max_filesize: 64M
php5_fpm_ini_post_max_size: 32M
php5_fpm_ini_date_timezone: "Europe/Berlin"
php5_fpm_ini_sendmail_path: "/usr/sbin/sendmail -t -i"
php5_fpm_ini_error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
php5_fpm_ini_display_errors: "On"
php5_fpm_ini_display_startup_errors: "Off"

#php5_fpm_pools:
#  - name: 'vagrant'
#    user: 'vagrant'
#    prefix: '/var/www/'
#    tmp_path: '/tmp/php5'
#    sessions_path: '/tmp/sessions'
#    logs_path: '/var/log/vhosts/'
#    project_paths: []
#    php_admin_value:
#      error_log: '/var/log/vhosts/php_errors.log'
#      max_input_vars: 5000
#      max_execution_time: 300
#      memory_limit: '256M'

php5_fpm_cronjobs: []
#  - name: Magento cron for live
#    user: 'vagrant'
#    cron_file: '{{ php5_fpm_pools.0.name }}'
#    job: /bin/sh {{ php5_fpm_pools.0.prefix }}/cron.sh &>> {{ php5_fpm_pools.0.logs_path }}/cron.log

mariadb_admin_user: 'root'
mariadb_admin_password: 'root'

# samba
samba_config_file: 'smb.conf'
samba_users:
  - name: vagrant
    password: vagrant