---
php5_fpm_remove_default_pool: false
nginx_remove_default_vhost: false

mariadb_users:
  - name: root
    password: root
    host: "%"
    priv: '*.*:ALL,GRANT' #SELECT,INSERT,UPDATE,DELETE,CREATE,ALTER,INDEX,DROP,CREATE TEMPORARY TABLES,CREATE_VIEW,SHOW VIEW,EVENT,TRIGGER,LOCK TABLES,REFERENCES'
    append_privs: true

php5_ini:
  expose_php: On
  memory_limit: 512M
  max_execution_time: 300
  max_input_time: 60
  max_input_vars: 5000
  realpath_cache_size: 32K
  realpath_cache_ttl: 120
  upload_max_filesize: 64M
  post_max_size: 32M
  date_timezone: "Europe/Berlin"
  sendmail_path: "/usr/sbin/sendmail -t -i"
  error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
  display_errors: "On"
  display_startup_errors: "Off"

#php5_fpm_pools:
#  - name: 'vagrant'
#    user: 'vagrant'
#    prefix: '/var/www/'
#    tmp_path: '/tmp/php5'
#    sessions_path: '/tmp/sessions'
#    logs_path: '/var/log/vhosts/'
#    project_paths: []
#    php_admin_value:
#      error_log: '/var/log/vhosts/php_errors.log'
#      max_input_vars: 5000
#      max_execution_time: 300
#      memory_limit: '256M'

php5_fpm_cronjobs: []
#  - name: Magento cron for live
#    user: 'vagrant'
#    cron_file: '{{ php5_fpm_pools.0.name }}'
#    job: /bin/sh {{ php5_fpm_pools.0.prefix }}/cron.sh &>> {{ php5_fpm_pools.0.logs_path }}/cron.log

mariadb_admin_user: 'root'
mariadb_admin_password: 'root'

# samba
samba_config_file: 'smb.conf'
samba_users:
  - name: vagrant
    password: vagrant