---
sudo: required
dist: trusty

language: python
python: "2.7"

env:
  - SITE=test.yml ANSIBLE_VERSION=latest
  - SITE=test.yml ANSIBLE_VERSION=2.1.0.0
  - SITE=test.yml ANSIBLE_VERSION=2.0.1.0
  - SITE=test.yml ANSIBLE_VERSION=2.0.0.2
  - SITE=test.yml ANSIBLE_VERSION=2.0.0.1
  - SITE=test.yml ANSIBLE_VERSION=2.0.0.0

matrix:
  allow_failures:
    - env: SITE=test.yml ANSIBLE_VERSION=2.0.0.2
    - env: SITE=test.yml ANSIBLE_VERSION=2.0.0.1
    - env: SITE=test.yml ANSIBLE_VERSION=2.0.0.0

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y curl

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install --no-binary ansible ansible; else pip install --no-binary ansible ansible==$ANSIBLE_VERSION; fi

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Install ansible-lint
  - pip install ansible-lint

  - ansible-galaxy install -r ansible/requirements.yml --ignore-errors --force

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i ansible/inventories/test ansible/playbook.yml --syntax-check"

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i ansible/inventories/test ansible/playbook.yml --connection=local --become"

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i ansible/inventories/test ansible/playbook.yml --connection=local --become
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # ansible-lint checks for best practice
  - ansible-lint ansible/playbook.yml

  # Make sure awscli is installed.
#  - >
#    cat /etc/motd | grep 'Jenkins'
#    && (echo 'motd is installed' && exit 0)
#    || (echo 'motd is not installed' && exit 1)

after_failure:
  - ansible-playbook -i ansible/inventories/test ansible/playbook.yml --connection=local --become
  - ansible --version
  - ansible-lint --version
  - ansible -i 127.0.0.1, -m setup all -c local

notifications:
  slack: ambimax:2MlPTX9bY9aPxCPhJGxHKIT6
  webhooks: https://galaxy.ansible.com/api/v1/notifications/